CREATE TABLE IF NOT EXISTS urls(
    id SERIAL PRIMARY KEY,
    userId INT NOT NULL,
    shortCode TEXT NULL,
    url TEXT NULL,
    createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (userId) REFERENCES users(id)
)