CREATE TABLE IF NOT EXISTS logs(
    id SERIAL PRIMARY KEY,
    urlId INT NOT NULL,
    qtd INT NULL,
    createdAt TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (urlId) REFERENCES urls(id)
)